# Generated by Django 3.2.18 on 2023-05-17 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
