# Generated by Django 3.2.18 on 2023-05-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20230516_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='numero',
            new_name='numero_habitacion',
        ),
        migrations.AddField(
            model_name='hotel',
            name='descripcion',
            field=models.CharField(default='party', max_length=200),
        ),
    ]
