# Generated by Django 3.2.18 on 2023-05-17 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20230516_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.hotel'),
        ),
    ]
