# Generated by Django 3.2.18 on 2023-05-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reservacion_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='rooms',
        ),
    ]
