# Generated by Django 3.2.18 on 2023-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230515_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_cedula',
            field=models.CharField(blank=True, choices=[('', 'Tipo de cedula'), ('1', 'Cedula de Ciudadania'), ('2', 'Tarjeta de Identidad'), ('3', 'Cedula de Extranjeria')], max_length=1),
        ),
    ]
