# Generated by Django 3.2.18 on 2023-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_cedula',
            field=models.CharField(blank=True, choices=[('1', 'Cedula de Ciudadania'), ('2', 'Tarjeta de Identidad'), ('3', 'Cedula de Extranjeria')], max_length=1),
        ),
    ]
