# Generated by Django 3.2.18 on 2023-05-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230514_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
